import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import {Input} from "~/components/Input";
import {FormGroup} from "~/components/FormGroup";
import React, {useState} from "react";
import {signIn, signOut, useSession} from "next-auth/react";
import {Button} from "~/components/Button";
import Image from "next/image";
import {useBuyCredits} from "~/hooks/useBuyCredits";

const GeneratePage: NextPage = () => {
    const { buyCredits } = useBuyCredits();

    const [form, setForm] = useState({
        prompt: '',
    });

    const [imageUrl, setImageUrl] = useState('');

    const generateIcon = api.generate.generateIcon.useMutation({
        onSuccess(data) {
            console.log('success', data);
            if (!data.imageUrl) {
                return;
            }
            setImageUrl(data.imageUrl);
        }
    });

    function updateForm(key:string) {
        return function(e: React.ChangeEvent<HTMLInputElement>) {
            setForm((prev) => ({
                ...prev,
                [key]: e.target.value
            })
        )}
    }

    const session = useSession();

    const isLoggedIn = !!session.data;

    function handleFormSubmit(e: React.FormEvent) {
        e.preventDefault();
        generateIcon.mutate({
            prompt: form.prompt
        });

        setForm({prompt: ''});
    }


    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col min-h-screen justify-center items-center">
                {
                    !isLoggedIn &&
                    <Button onClick={() => {
                        signIn().catch(console.error)
                    }}>Login</Button>
                }
                {
                    isLoggedIn && (
                        <>
                            <Button onClick={() => {
                                buyCredits().catch(console.error)
                            }}>Buy more credits</Button>
                            <Button onClick={() => {
                                signOut().catch(console.error)
                            }}>Logout</Button>
                        </>

                    )
                }
                <form className="flex flex-col gap-4"
                    onSubmit={handleFormSubmit}
                >
                    <FormGroup>
                        <label htmlFor="">Prompt</label>
                        <Input value={form.prompt} onChange={updateForm('prompt')} />
                    </FormGroup>
                    <Button className="bg-blue-400 hover:bg-blue-500 px-4 py-2 rounded">Submit</Button>
                </form>

                <Image
                    src={imageUrl}
                    alt={"an image of your prompt"}
                    width={"100"}
                    height={"100"}
                />
            </main>
        </>
    );
};

export default GeneratePage;
